In [1]:
import numpy as np


In [33]:
# One-dimensional array

a=np.array([0,1,2,3])
print(a)
print(type(a))
print(a.shape)

[0 1 2 3]
<class 'numpy.ndarray'>
(4,)


In [6]:
print("first Element:", a[0])
print("second Element:", a[1])
print("Third Element:", a[2])

first Element: 0
second Element: 1
Third Element: 2


# Creating 2D Array

In [36]:
b=np.array([[1,2,3,4],[4,5,6,7]])
print(b)

b.shape #for rows and column
b.ndim #for dimension

[[1 2 3 4]
 [4 5 6 7]]


2

### accessing the element from 2d array

In [19]:
print("Element at row1, column2:",b[0, 1])
print("Entire row at index 1:", b[1])
print("Entire column at index 2:", b[:, 2])
print("element of second row,column3:",b[1,2])
b[1, 2] = 10
print("updated element of row 1 column2:",b[1,2])
b

Element at row1, column2: 2
Entire row at index 1: [ 4  5 10  7]
Entire column at index 2: [ 3 10]
element of second row,column3: 10
updated element of row 1 column2: 10


array([[ 1,  2,  3,  4],
       [ 4,  5, 10,  7]])

In [9]:
L = range(1000)
%timeit [i**2 for i in L]
#The purpose of this comparison is to show the performance benefit of 
#using NumPy for such operations. NumPy's vectorized operations are generally
#faster than traditional Python loops or list comprehensions because 
#they are implemented in compiled C code, which is more efficient for numerical computations.

1.08 ms ± 7.16 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
a = np.arange(1000)
%timeit a**2

4.03 µs ± 93.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
c=np.array([[1,2,3],[4,5,6],[0,1,2]])
c
print(c[2,0])
print(c[1,1])
print(c[2,2])

print(c[0,0],c[1,1],c[2,2])#digonal elemments 



0
5
2
1 5 2


In [47]:
# Create a 3D array
d = np.array([[[1, 2, 3], [4, 5, 6], [0, 1, 2]]])

# Access each element of the matrix
element_00 = d[0, 0, 0]
element_01 = d[0, 0, 1]
element_02 = d[0, 0, 2]
element_10 = d[0, 1, 0]
element_11 = d[0, 1, 1]
element_12 = d[0, 1, 2]
element_20 = d[0, 2, 0]
element_21 = d[0, 2, 1]
element_22 = d[0, 2, 2]

print("Element at (0,0,0):", element_00)
print("Element at (0,0,1):", element_01)
print("Element at (0,0,2):", element_02)
print("Element at (0,1,0):", element_10)
print("Element at (0,1,1):", element_11)
print("Element at (0,1,2):", element_12)
print("Element at (0,2,0):", element_20)
print("Element at (0,2,1):", element_21)
print("Element at (0,2,2):", element_22)


Element at (0,0,0): 1
Element at (0,0,1): 2
Element at (0,0,2): 3
Element at (0,1,0): 4
Element at (0,1,1): 5
Element at (0,1,2): 6
Element at (0,2,0): 0
Element at (0,2,1): 1
Element at (0,2,2): 2


### Play with Matrix


In [48]:

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.05327037 0.83621964]
 [0.15465591 0.22284902]]


### Slicing of an Array

In [54]:

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
"""The code b = a[:2, 1:3] creates a new array b by slicing the original array a. Here's what each part of the slicing means:

[:2]: This selects the first two rows of the array a.
[1:3]: This selects columns 1 and 2 (up to, but not including, index 3) of each selected row.
So, b will be a 2x2 subarray of a, containing the following elements:

a[0, 1], a[0, 2] (from the first row of a),
a[1, 1], a[1, 2] (from the second row of a).
In other words, b will contain elements from the first two rows of a, but only columns 1 and 2 of each row.
"""

[[2 3]
 [6 7]]


"The code b = a[:2, 1:3] creates a new array b by slicing the original array a. Here's what each part of the slicing means:\n\n[:2]: This selects the first two rows of the array a.\n[1:3]: This selects columns 1 and 2 (up to, but not including, index 3) of each selected row.\nSo, b will be a 2x2 subarray of a, containing the following elements:\n\na[0, 1], a[0, 2] (from the first row of a),\na[1, 1], a[1, 2] (from the second row of a).\nIn other words, b will contain elements from the first two rows of a, but only columns 1 and 2 of each row.\n"

In [53]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

77
77


In [55]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


## Q1

In [61]:
a=np.array([[1,2],[3,4],[5,6]])
# An example of integer array indexing.
# The returned array will have shape (3,) and print [1,4,5]
#print(a[0,0],a[1,1],a[2,0])
print(a[[0,1,2],[0,1,0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


### Datatype in numpy


In [62]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


### Array maths

In [63]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [64]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [65]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [66]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### IMAGE OPERATION

In [4]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img = imread('https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_tinted)

ImportError: cannot import name 'imread' from 'scipy.misc' (C:\Users\HP\anaconda3\lib\site-packages\scipy\misc\__init__.py)

In [2]:
!pip install scipy

In [7]:
import imageio
import numpy as np

# Read an JPEG image into a numpy array
img = imageio.imread('https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png')
# Print the shape of the image array
print("Image shape:", img)

C:\Users\HP\AppData\Local\Temp\ipykernel_12144\4292729253.py:5: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img = imageio.imread('https://images.rawpixel.com/image_png_800/czNmcy1wcml2YXRlL3Jhd3BpeGVsX2ltYWdlcy93ZWJzaXRlX2NvbnRlbnQvcHUyMzMxNjM2LWltYWdlLTAxLXJtNTAzXzMtbDBqOXFrNnEucG5n.png')


Image shape: [[[238 238 238]
  [238 238 238]
  [238 238 238]
  ...
  [248 248 248]
  [255 255 255]
  [254 254 254]]

 [[238 238 238]
  [238 238 238]
  [238 238 238]
  ...
  [248 248 248]
  [255 255 255]
  [254 254 254]]

 [[238 238 238]
  [238 238 238]
  [238 238 238]
  ...
  [248 248 248]
  [255 255 255]
  [254 254 254]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [247 247 247]
  [238 238 238]
  [238 238 238]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [247 247 247]
  [238 238 238]
  [238 238 238]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [247 247 247]
  [238 238 238]
  [238 238 238]]]


In [8]:
def add(a,b):
    ans=a+b
    print(ans)

a=5
b=7
add(a,b)

12


In [11]:
name = input()                  # Reading input from STDIN

print('Hi, %s.' % name)         # Writing output to STDOUT


 5


Hi, 5.Hi, 5.


In [12]:
# Read input from STDIN
input_length = int(input().strip())
input_string = input().strip()

# Print the length of the string
print(len(input_string))

# Print the input string
print(input_string)


 5
 hellowordl


10
hellowordl


In [17]:
def first_element(l):
    return l[0]
x=[1,2,3]
print(first_element(x))



    

2


In [31]:
def list_min(l):
    mini=l[0]
    for i in range (len(l)):
        if(l[i]<mini):
            mini=l[i]
    return mini 
def list_max(l):
    max=l[0]
    for i in range(len(l)):
        if l[i]>max:
            max=l[i]
    return max 
def list_appendbefore(l,z):
    newl=[]
    for i in range(len(z)):
        newl.append(z[i])
    for i in range(len(l)):
        newl.append(l[i])
    return newl
    
def list_appended(l,z):
    newl=[]
    for i in range(len(l)):
        newl.append(l[i])
    for i in range(len(z)):
        newl.append(z[i])
    return newl
def list_average(l):
    sum=0
    for i in range(len(l)):
        sum=sum+l[i]
    avg=sum/len(l)
    return avg

l=[1,2,3,5,-10,-5,4,2,3,13]
z=[10,20,30]
print(list_min(l))
print(list_max(l))
print(list_appendbefore(l,z))
print(list_appended(l,z))
print(list_average(l))


-10
13
[10, 20, 30, 1, 2, 3, 5, -10, -5, 4, 2, 3, 13]
[1, 2, 3, 5, -10, -5, 4, 2, 3, 13, 10, 20, 30]
1.8


In [30]:
list_max([1,2,3,-10,8,0])

8

In [32]:
#find out the minimum most element in the list l
#append that to a new list x
#remove the minimum from the original list l.
def obvious_sort(l):
    x=[]
    while(len(l)>0):
        mini=l[0]
        for i in range(len(l)):
            if l[i]<mini:
                mini=l[i]
        x.append(mini)
        l.remove(mini)
    return x
l=[20,30,11,5,2,3,-3,2]
print(obvious_sort(l))
            

[-3, 2, 2, 3, 5, 11, 20, 30]


In [39]:
#we just learn that breaking our problem into smaller modules and solving them 
#makes it easy on our mind. 
#method 2 that is used for best and fast result 
def min_list(l):
    mini=l[0]
    for i in range(len(l)):
        if l[i]<mini:
            mini=l[i]
    return mini
def obvious_sort1(l):
    x=[]
    while len(l)>0:
        mini=min_list(l)
        x.append(mini)
        l.remove(mini)
    return x 
l=[20,30,11,5,2,3,-3,2]
l=[20,30,11,5,2,3,-3,2]
print(min_list(l)) #it gives the minimum value from the list 
print(obvious_sort1(l))

-3
[-3, 2, 2, 3, 5, 11, 20, 30]


In [8]:
def square(a):
    return a ** 2

# Taking input in a single line, separated by spaces
x, y, z = map(int, input().split())

# Checking if the numbers form a right triangle
if square(x) + square(y) == square(z):
    print(f'{x}, {y}, and {z} form the sides of a right triangle with {z} as the hypotenuse')
else:
    print(f'{x}, {y}, and {z} do not form the sides of a right triangle')


 3 4 5


3, 4, and 5 form the sides of a right triangle with 5 as the hypotenuse


**Recursion**

In [17]:
n=10
ans=0
for i in range(n):
    ans=ans+(i+1)
print(ans)

55


In [3]:
def sum(n):
    ans=0
    for i in range(n):
        ans=ans+(i+1)
    return ans
sum(10)

55

In [6]:
#recursion in python means do it again and again 
#function under the function 
def sum(n): #here sum is a diffrent function that we created 
    if n==1:
        return 1 
    else:
        return n+ sum(n-1)  #but here is default sum function by intrepreter 
sum(5)
        

15

In [13]:
#compound interest for interst 10 %
def comp(p,n):
    if n==1:
        return p*(1.1)
    else:
        return (comp(p,n-1))*1.1
        
comp(100,1)


110.00000000000001

In [30]:
def fact(n):
    if n==1:
        return 1 
    elif n==0:
        return 1 
    elif n<0:
        return 'Not defined'
    else:
        return fact(n-1)*n
fact(-4)

'Not defined'

In [34]:
def myFunction1(x):
    x=x*2
    print('value of x in function 1',x)
def myFunction2(x):
    x=x*3
    print('value of x in function2',x)
x=5
print('value of the x before the function call',x)
myFunction1(x)
myFunction2(x)
print('value of x after function call',x)

value of the x before the function call 5
value of x in function 1 10
value of x in function2 15
value of x after function call 5


In [39]:
s=set(range(10))
s
p={1,2,4,5,6,1,2,4}
print(type(p))
print(p) #set remove the duplicate element from the set and follow the conventional rule that set has only unique element. 

<class 'set'>
{1, 2, 4, 5, 6}


In [40]:
5 in p


True

In [44]:
import sys
l=[]
l1=[0]
l2=[0,1]
print(sys.getsizeof(l))
print(sys.getsizeof(l1))
print(sys.getsizeof(l2))



56
64
72


In [46]:
x=list(range(100))
s=set(range(100))
print(x)
print(s)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99}


In [47]:
sys.getsizeof(x) #it takes less space in memory than set 

856

In [48]:
sys.getsizeof(s) # its takes more spaces in memory for the same no of element 

8408

In [49]:
#thats why searching in set becomes easy and difficult in list because you cant
#search element in a list easily but in set we can easily 
28 in s 

True

In [57]:
200 in s

False

In [59]:
x[0]

0

In [60]:
x[1]

1

In [61]:
s[1] # we cant use set as a list and access its element by index 


TypeError: 'set' object is not subscriptable

In [66]:
d={}
d['Rohit']=9834232322
d['Muskan']=3422332233
d['keshav']=4555667788
print(d)

{'Rohit': 9834232322, 'Muskan': 3422332233, 'keshav': 4555667788}


In [69]:
d['Rohit']

9834232322